language: python
python:
  - "2.6"
  - "2.7"
# command to run tests
script: python testproject/manage.py test wiki
install:
  - pip install -r .travis/requirements_1.4.txt --use-mirrors
  - pip install -r .travis/requirements_1.5.txt --use-mirrors
script:
  - python -W error:"":"":0 testproject/manage.py test

