language: python
# See tox.ini for env list
env:
- TOXENV=py26-django15
- TOXENV=py26-django16
- TOXENV=py27-django15
- TOXENV=py27-django16
- TOXENV=py27-django17
- TOXENV=py27-django18
- TOXENV=py34-django15
- TOXENV=py34-django16
- TOXENV=py34-django17
- TOXENV=py34-django18
install:
  - pip install tox coveralls
script:
  - tox
  - coverage run --source=wiki setup.py test
notifications:
  irc:
    - "irc.freenode.org#django-wiki"
after_success:
  coveralls

